export const DETECT_DEVICE = 'DETECT_DEVICE';

export const SERVER_RENDERED = 'SERVER_RENDERED';
export const INIT_SUCCESS = 'INIT_SUCCESS';

export const INIT_SETTING = 'INIT_SETTING';
export const INIT_SETTING_SUCCESS = 'INIT_SETTING_SUCCESS';

export const IN_PROCESS = 'IN_PROCESS';
export const PROCESS_COMPLETE = 'PROCESS_COMPLETE';
export const PUT_SUCCESS = 'PUT_SUCCESS';
export const PUT_ERROR = 'PUT_ERROR';
export const PUT_WARNING = 'PUT_WARNING';

export const PUSH_METADATA = 'PUSH_METADATA';

/*
 * AUTH
 * */
export const LOGIN = 'LOGIN';
export const LOGIN_WITH_EMAIL = 'LOGIN_WITH_EMAIL';
export const LOGIN_WITH_FACEBOOK = 'LOGIN_WITH_FACEBOOK';
export const LOGIN_WITH_GOOGLE = 'LOGIN_WITH_GOOGLE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_EMAIL = 'REGISTER_EMAIL';
export const REGISTER_EMAIL_SUCCESS = 'REGISTER_EMAIL_SUCCESS';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export const VERIFY_EMAIL = 'VERIFY_EMAIL';

export const SEND_EMAIL_FORGOT = 'SEND_EMAIL_FORGOT';
export const SEND_EMAIL_FORGOT_SUCCESS = 'SEND_EMAIL_FORGOT_SUCCESS';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';

export const EDIT_PROFILE = 'EDIT_PROFILE';

export const CLEAR_AUTH_WAITING = 'CLEAR_AUTH_WAITING';

/*
 * MOVIE
 * */

export const GET_FILTER_MOVIE = 'GET_FILTER_MOVIE';
export const PUSH_FILTER_MOVIE = 'PUSH_FILTER_MOVIE';
export const CLEAR_MOVIE = 'CLEAR_MOVIE';

export const GET_RELATED_STAR = 'GET_RELATED_STAR';
export const PUSH_RELATED_STAR = 'PUSH_RELATED_STAR';
export const CLEAR_RELATED_STAR = 'CLEAR_RELATED_STAR';

export const GET_DETAIL_MOVIE = 'GET_DETAIL_MOVIE';
export const PUSH_DETAIL_MOVIE = 'PUSH_DETAIL_MOVIE';

/*
 * BANNER
 * */

export const INIT_BANNER = 'INIT_BANNER';
export const INIT_BANNER_SUCCESS = 'INIT_BANNER_SUCCESS';

export const GET_BANNER = 'GET_BANNER';

export const CLOSE_BANNER = 'CLOSE_BANNER';
export const CLOSE_BANNER_SUCCESS = 'CLOSE_BANNER_SUCCESS';
