export default {
    NOT_FOUND: 'Not Found.',
    UNKNOWN: 'Unknown.',
    DATA_LOAD_FAILED: 'Data Load Failed.',
    UNAUTHORIZED: 'Unauthorized.',
    TOKEN_EXPIRED: 'Token Expired.',
    SIGNATURE_FAILED: 'Signature Failed.',
    SIGNATURE_EXPIRED: 'Signature Expired..',
    EXPIRED: 'Expired.',
    RECAPTCHA: 'Recaptcha.',
    OTP_FAILED: 'OTP Failed.',
    PERMISSION: 'Permission.',
    PASSWORD_FAILED: 'Password Failed.',
    USER_NOT_FOUND: 'User Not Found.',
    USER_BLOCKED: 'User Blocked.',
    USER_ALREADY_EXISTS: 'User Already Exists.',
    FILE_EMPTY: 'File Empty.',
    FILE_TYPE: 'File Type.',
    UNIQUE: 'Unique.',
    NOT_EXISTS: 'Not Exists.',
    EMAIL_FORMAT: 'Email Format.',
    JSON_FORMAT: 'Json Format.',
    SLUG_FORMAT: 'Slug Format.',
    PHONE_NUMBER_FORMAT: 'Phone Number Format.',
    INT_FORMAT: 'Int Format.',
    NOT_EMPTY: 'Not Empty.',
    NOT_NULL: 'Not Null.',
    EXISTS_ITEMS: 'Exists Items.',
    MISSING_PARAM: 'Missing Param.',
    NOT_INIT_METHOD: 'Not Init Method.',
    PROCESSING: 'Processing.',
    BLOCKED: 'Blocked.',
    VALIDATE: 'Validate.',
    ERROR_SERVER: 'Error Server.',
    LIMIT_FILE_SIZE: 'Limit File Size.',
    LOGIN_FAILED: 'Login Failed.',
    USER_NOT_VERIFIED: 'User Not Verified.',
    PASSWORD_EMPTY: 'Password Empty.',
    PASSWORD_ALREADY: 'Password Already.',
};
